services:
  postgres:
    container_name: postgres-dev
    image: postgres:18
    restart: always
    ports:
      - 6432:5432
    networks:
      - database
    volumes:
      - postgres-dev:/var/lib/postgresql/data
      - ./conf/postgres/create-user-and-db.sh:/docker-entrypoint-initdb.d/create-user-and-db.sh
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: "Europe/Rome"
      PGTZ: "Europe/Rome"

  redis:
    container_name: redis-dev
    image: redis:latest
    restart: always
    ports:
      - 7379:6379
    networks:
      - database
    volumes:
      - redis-dev:/data

  nginx:
    container_name: nginx-dev
    image: nginx:latest
    restart: always
    volumes:
      - /tmp:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data

networks:
  database:
    name: database

volumes:
  postgres-dev:
    name: postgres-dev
  redis-dev:
    name: redis-dev
  portainer:
    name: portainer
