services:
  postgres:
    container_name: postgres-dev
    image: postgres:18
    restart: always
    ports:
      - 6432:5432
    networks:
      - database
    volumes:
      - postgres-dev:/var/lib/postgresql/data
      - ./conf/postgres/create-user-and-db.sh:/docker-entrypoint-initdb.d/create-user-and-db.sh
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: "Europe/Rome"
      PGTZ: "Europe/Rome"

  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data

networks:
  database:
    name: database

volumes:
  postgres-dev:
    name: postgres-dev
  portainer:
    name: portainer
