name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build TypeScript
        run: npm run build

      - name: Copy project to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "."
          target: "/opt/custom-services/fastify-core-starter"

      - name: Create .env file on VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cat > /opt/custom-services/fastify-core-starter/.env <<EOF
            NODE_ENV=production
            APP_ENV=production
            APP_NAME=fastify-core-starter
            SERVER_ADDRESS=localhost
            SERVER_PORT=3000
            LOG_LEVEL=info
            PG_HOST=${{ secrets.PG_HOST }}
            PG_PORT=${{ secrets.PG_PORT }}
            PG_DB=${{ secrets.PG_DB }}
            PG_USER=${{ secrets.PG_USER }}
            PG_PW=${{ secrets.PG_PW }}
            EOF

      - name: SSH into VPS & restart service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /opt/custom-services/fastify-core-starter
            npm ci
            npm run build
            npm run applyMigrations
            pm2 startOrRestart ecosystem.config.cjs
            pm2 save
