name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build TypeScript
        run: npm run build

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H YOUR.SERVER.IP >> ~/.ssh/known_hosts
        env:
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}

      - name: Copy project to VPS with rsync
        run: |
          mkdir -p /opt/fastify-service
          rsync -avz -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" \
            --exclude node_modules \
            --exclude .git \
            --exclude .vscode \
            --exclude dist \
            --exclude doc \
            --exclude local-stack \
            ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/opt/fastify-service

      - name: Create .env file on VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cat > /opt/fastify-service/.env <<EOF
            NODE_ENV=production
            APP_ENV=production
            APP_NAME=fastify-core-starter
            SERVER_ADDRESS=localhost
            SERVER_PORT=3000
            LOG_LEVEL=info
            PG_HOST=${{ secrets.PG_HOST }}
            PG_PORT=${{ secrets.PG_PORT }}
            PG_DB=${{ secrets.PG_DB }}
            PG_USER=${{ secrets.PG_USER }}
            PG_PW=${{ secrets.PG_PW }}
            EOF

      - name: SSH into VPS & restart service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /opt/fastify-service
            npm ci
            npm run build
            npm run applyMigrations
            sudo systemctl restart fastify-app.service
